branches:
  only:
  - master
language: generic
notifications:
  email: false
script:
- |
  git config user.name "Travis CI" &&
  git config user.email "travis@localhost" &&
  git remote remove origin &&
  git remote add origin https://$GITHUB_API_KEY@github.com/spacewalkproject/spacewalk-wiki.git &&
  git remote add upstream https://$GITHUB_API_KEY@github.com/spacewalkproject/spacewalk.wiki.git &&
  git fetch origin &&
  git fetch upstream &&
  git rebase upstream/master &&
  git push -f origin HEAD:master &&
  git push upstream HEAD:master
